---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-porkbun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-porkbun
subjects:
- kind: ServiceAccount
  name: cert-manager-webhook-porkbun
  namespace: cert-manager-webhook-porkbun
